/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_Dietecien (void);
GtkWidget* create_window1 (void);
GtkWidget* create_admin (void);
GtkWidget* create_adherant (void);
GtkWidget* create_kinee (void);
GtkWidget* create_nutretioniste (void);
GtkWidget* create_coach (void);
